name: MJML EEx CI

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SHELL: sh

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: "1.16.3"
          otp-version: "26.2"
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Install dependencies
        run: mix deps.get
      - name: Restore PLT cache
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Mix Formatter
        run: mix format --check-formatted
      - name: Check for compiler warnings
        run: mix compile --warnings-as-errors
      - name: Credo strict checks
        run: mix credo --strict
      - name: Doctor documentation checks
        run: mix doctor

  unit_test:
    name: Run ExUnit tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        version:
          - otp: 26.2
            elixir: 1.15.8
          - otp: 26.2
            elixir: 1.16.3
          - otp: 27.0
            elixir: 1.17.0-rc.1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.version.elixir }}
          otp-version: ${{ matrix.version.otp }}
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Restore dependencies cache
        uses: actions/cache@v2
        with:
          path: deps
          key: ${{ runner.os }}-mix-v2-${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ runner.os }}-mix-v2-
      - name: Install dependencies
        run: mix deps.get
      - name: Install Node MJML compiler
        run: npm install -g mjml
      - name: Set MJML path env var
        run: echo "$(npm bin)" >> $GITHUB_PATH
      - name: ExUnit tests
        env:
          MIX_ENV: test
          SHELL: /bin/bash
        run: mix coveralls.github
